# Use the official Python image from Docker Hub
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt ./

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY src/ ./

# Copy other necessary files or directories
COPY data/ data/

# Command to run the application
CMD ["streamlit", "run", "app.py","--server.address=0.0.0.0", "--server.port=8501"]
